### ISSUE TITLE
Condition error

### ISSUE THREAD

**Issue by im-n1** [fubarhouse/ansible-role-rust#20]
When I run your role with:

```yaml
  roles:
    - role: fubarhouse.rust
      vars:
        rust_version: 1.37
        shell_profiles:
          - .zprofile
        cargo_items:
          - bat
          - lsd
          - pug
          - racer
          - rustfmt-nighty
          - sass-rs
          - spruce
      become: true
```

I get (screenshot taken from virtual, sorry):
![image](https://user-images.githubusercontent.com/198654/64402267-9a98ce00-d074-11e9-883a-2dbff86dbe65.png)

**Comment by fubarhouse** [comment]
Thanks for reporting!
It seems the logic needs to be updated - I'll make it happen.

**Comment by fubarhouse** [comment]
Changes introduced in branch `issue/20` will fix this issue.
You will however need to change `rust_version` to `1.37.0`.

Please test when possible.

```
meta:
  timestamp: 2019-09-08T22:10:05.607375+10:00
  repository: git@github.com:fubarhouse/ansible-role-rust.git
  commithash: 104550badc276ddef02d83c796c4d38882e89055
  localchanges: true
  reportfile: report.yml
ansible:
  config:
    hostpath: /Users/karl/PycharmProjects/ansible-role-rust
    inventory: ""
    remotepath: /etc/ansible/roles/role_under_test
    extrarolespath: ""
    librarypath: ""
    requirementsfile: ""
    playbookfile: tests/playbook.yml
    remote: false
    verbose: true
    quiet: false
  distribution:
    cid: ""
    name: ubuntu1804
    privileged: true
    container: fubarhouse/docker-ansible:bionic
    user: fubarhouse
    distro: ubuntu1804
    family:
      name: Ubuntu
      initialise: /sbin/init
      volume: /sys/fs/cgroup:/sys/fs/cgroup:ro
  hosts:
  - localhost
  syntax: true
  requirements: false
  run:
    result: true
    time: 3m53.524527879s
  idempotence:
    result: true
    time: 10.799883279s
docker:
  run: true
  kill: true
  volumes:
  - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - /Users/karl/PycharmProjects/ansible-role-rust:/etc/ansible/roles/role_under_test
  - /Users/karl/PycharmProjects/ansible-role-rust:/etc/ansible/roles/ansible-role-rust
```
